Add a CLI tool and build it with GH actions
Cxbx-Reloaded/XbSymbolDatabase pull request #108
Opened 2020-09-03 20:30 UTC by thrimbor

This adds a cli tool, which can be used to run symbol detection on an XBE. The actual tool was written by @mborgerson, I only tweaked the CMakeLists to fix building under some Linux distributions and to make building the tool optional (as Cxbx-Reloaded probably doesn't want it built). The Actions file is also his work, I slightly modified it to ignore the readme (like the current Actions file does) and make it use checkout@v2.

The Actions file also uploads the created CLI tool binaries as an artifact. This is then used in @mborgerson's Ghidra XBE plugin, where this artifact is downloaded and included to provide symbol detection.

2020-09-03 23:24 UTC, RadWolfie commented
I do not plan to add artifacts, which is temporary storage. It will only hold for 3 months. build.yml file doesn't make sense to me nor is optimized. Please restore the workflow then simply just add `-D BUILD_TOOL=ON` within cmake-parameters variable.

They can build their own binaries then make a release in order to store permanently. Currently, there are a lot of changes that needs to be done plus optimization.

P.S. I don't have time to at least possibility setup a semantic versioning to handle all of this work in order to make progressive releases.

2020-09-03 23:41 UTC, RadWolfie commented on CMakeLists.txt
> +if(BUILD_TOOL)
Keep in mind, I will move this changes into projects folder.

The goal for each project, such as library, cli tool, and unit test cmake files go into **projects** folder. Plus source files will likely go into their own folder due to multiple projects bundle in one repository. i.e.
```
src/cli/...
src/lib/...
src/unittest/...
```
or without src part.

2020-09-04 07:28 UTC, thrimbor commented
> I do not plan to add artifacts, which is temporary storage. It will only hold for 3 months.

I'm aware it's temporary, but I don't see how that's a problem. Rolling releases would probably be better, but artifacts at least are enough for building the Ghidra XBE plugin, and also allow people to, say, test the changes done in a PR locally without having to build themselves.

> build.yml file doesn't make sense to me

What about it doesn't make sense?

> They can build their own binaries then make a release in order to store permanently.

Are you saying that other projects should maintain their own forks of XbSymbolDatabase and add this functionality there? If yes, why? Imho this should be solved upstream instead.

2020-09-04 08:56 UTC, RadWolfie commented
> I'm aware it's temporary, but I don't see how that's a problem. Rolling releases would probably be better, but artifacts at least are enough for building the Ghidra XBE plugin, and also allow people to, say, test the changes done in a PR locally without having to build themselves.

I don't see the problem for fork repos to have their own artifacts and it's not a big issue either. We do build ourselves to verify the result. Since not every compiler/platform will build the same. And I have to pull the pull request branch locally to able verify with local, major wip, unit test tool.

> What about it doesn't make sense?

1. It's not optimized.
2. Has hardcode hacks which I don't accept.
3. Doesn't make sense to rename them to tool_name.____64.____. Since I don't see the purpose for this. Putting them in a folder name would be more common sense to me. (Same as reason 2.)
4. Too much effort to maintenance per platform.
5. Easy to miss corrections for all three or more platforms. (Same as reason 4.)

> Are you saying that other projects should maintain their own forks of XbSymbolDatabase and add this functionality there? If yes, why? Imho this should be solved upstream instead.

That's not what I'm saying, they can create a new branch, with workflow, then simply make merge commit that contain latest changes to produce pushed artifacts "temporary".

2020-09-04 09:01 UTC, RadWolfie commented on .github/workflows/build.yml
> +          Rename-Item -Path "build\${{ matrix.configuration }}\XbSymbolDatabaseTool.exe" -NewName "XbSymbolDatabaseTool.win64.${{ matrix.configuration }}.exe"
`-A Win32` will output 32-bit executable on build, not 64-bit executable by the way.

2020-09-04 10:08 UTC, RadWolfie requested changes
I found some changes require in cli's source code. The rest looks good.

2020-09-04 10:08 UTC, RadWolfie commented on cli.c
> +        fprintf(stderr, "%d libraries\n", lib_hdr.count);
```suggestion
        fprintf(stderr, "%u libraries\n", lib_hdr.count);
```
Proper format for unsigned integer is %u.

2020-09-04 10:08 UTC, RadWolfie commented on cli.c
> +            fprintf(stderr, "  %s\n", sec_hdr.filters[i].name);
Same ideal with lib_hdr's filter[x].name need fixed size length for safe output.

2020-09-04 11:38 UTC, thrimbor commented
> > I'm aware it's temporary, but I don't see how that's a problem. Rolling releases would probably be better, but artifacts at least are enough for building the Ghidra XBE plugin, and also allow people to, say, test the changes done in a PR locally without having to build themselves.
> 
> I don't see the problem for fork repos to have their own artifacts and it's not a big issue either. We do build ourselves to verify the result. Since not every compiler/platform will build the same. And I have to pull the pull request branch locally to able verify with local, major wip, unit test tool.

I do - it requires forking a repo to add functionality that should be provided upstream. And ofc maintainers have to check the code out locally, but there's no need to force everybody else to do the same.

>     2. Has hardcode hacks which I don't accept.

Can you please be more specific?

> > Are you saying that other projects should maintain their own forks of XbSymbolDatabase and add this functionality there? If yes, why? Imho this should be solved upstream instead.
> 
> That's not what I'm saying, they can create a new branch, with workflow, then simply make merge commit that contain latest changes to produce pushed artifacts "temporary".

I'm confused - you say it's not what you were saying, but then you describe what I just said.

> In my opinion, learning more about the matrix method would be ideal how

I'm just going to ignore that condescending statement.

2020-09-04 12:31 UTC, RadWolfie commented
> I do - it requires forking a repo to add functionality that should be provided upstream. And ofc maintainers have to check the code out locally, but there's no need to force everybody else to do the same.

Who is everybody else? There are little maintenance happen here. Last updated before you create pull requests were 7 months ago.

> Can you please be more specific?

I'm not going to continue with this discussion. If you want my help to fix the workflow optimization, then let's talk in discord.

> I'm confused - you say it's not what you were saying, but then you describe what I just said.

The way you described is forked repository users will continue to do their work and not upstream plus "add this functionality". That's how I read it from your reply.
 
> I'm just going to ignore that condescending statement.

It's a suggestion by the way. It's too much work for us to maintenance without using matrix method. Beside it should be in separate pull request anyway.

2020-09-04 20:42 UTC, Margen67 commented on .github/workflows/build.yml
> +        shell: cmd
This line isn't needed.

2020-09-04 20:43 UTC, Margen67 commented on .github/workflows/build.yml
> +      - name: Generate cmake files
```suggestion
      - name: Generate CMake files
```

2020-09-04 21:03 UTC, Margen67 commented on .github/workflows/build.yml
> +          cmake --build build/ --config ${{ matrix.configuration }}
```suggestion
          working-directory: build
          cmake --build . --config ${{ matrix.configuration }} -j $env:NUMBER_OF_PROCESSORS
```

2020-09-04 21:05 UTC, Margen67 commented on .github/workflows/build.yml
> +          cmake --build build/ --config ${{ matrix.configuration }}
```suggestion
        working-directory: build
        run: |
          cmake --build . --config ${{ matrix.configuration }} -j $env:NUMBER_OF_PROCESSORS
```

2020-09-28 09:55 UTC, RadWolfie commented
Since I have permission to fix this pull request. However, local push to this pull request isn't working for me. You'll need to do hard reset for 2-3 commits. Then pull rebased branch, from https://github.com/RadWolfie/XbSymbolDatabase/tree/clitool-fixup, with fixes from my fork repo.

I have pinged this message to @thrimbor on discord. Yet I had not seen any activity from this pull request, so I'm posting it here.

2020-12-15 13:16 UTC, thrimbor commented
I integrated your changes now.

2020-12-16 15:42 UTC, RadWolfie approved these changes
All checks are passing, comparison with containing fixes do match, and verified CLIs are built and installed base on artifact folder.

2020-12-16 15:42 UTC, merged